// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDehVNpn5GQORNMCm_kh4XZOG62aZDMm1w',
    appId: '1:711979799277:web:13cd0c7c81eea4d3d672e4',
    messagingSenderId: '711979799277',
    projectId: 'sell-it-76111',
    authDomain: 'sell-it-76111.firebaseapp.com',
    storageBucket: 'sell-it-76111.appspot.com',
    measurementId: 'G-HGDW2HCDEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA7yH06Dh5MeZGpnA58sOCHvj2y-DwH8o',
    appId: '1:711979799277:android:1d4786fcc6535f33d672e4',
    messagingSenderId: '711979799277',
    projectId: 'sell-it-76111',
    storageBucket: 'sell-it-76111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv12YennzL_DTlzl9pkcmftQbdyN0Y8jY',
    appId: '1:711979799277:ios:47fae7ee9a4e4c06d672e4',
    messagingSenderId: '711979799277',
    projectId: 'sell-it-76111',
    storageBucket: 'sell-it-76111.appspot.com',
    iosBundleId: 'com.example.sellit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv12YennzL_DTlzl9pkcmftQbdyN0Y8jY',
    appId: '1:711979799277:ios:47fae7ee9a4e4c06d672e4',
    messagingSenderId: '711979799277',
    projectId: 'sell-it-76111',
    storageBucket: 'sell-it-76111.appspot.com',
    iosBundleId: 'com.example.sellit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDehVNpn5GQORNMCm_kh4XZOG62aZDMm1w',
    appId: '1:711979799277:web:5c2988d0512ed3ebd672e4',
    messagingSenderId: '711979799277',
    projectId: 'sell-it-76111',
    authDomain: 'sell-it-76111.firebaseapp.com',
    storageBucket: 'sell-it-76111.appspot.com',
    measurementId: 'G-85CPBDBLP8',
  );
}
